
//Global variables.
var index1 = 0;
var index2 = 0;
var index3 = 0;
var allProducts = [];


//Creates each prodcut instance. Adds to allProducts array.
function createProduct(img, name){
    this.img = img;
    this.shown = 0;
    this.voted = 0;
    this.name = name;
    this.addToArray(); //Adds to product to array.
    console.log(this.name + " product has been created");
    console.log(allProducts)
};

//Method on createProduct constructor that adds new product to an array.
createProduct.prototype.addToArray = function(){
    allProducts.push(this);
};

//Function that generate 3 unique random integers between 0 and allProducts.length.
function choose3RandomNums(){ 
  index1 = Math.floor(Math.random() * allProducts.length );
  index2 = Math.floor(Math.random() * allProducts.length );
  while(index1 === index2){//Picks new index if index grnerated is already chosen.
  index2 = Math.floor(Math.random() * allProducts.length );
  };
  index3 = Math.floor(Math.random() * allProducts.length );
  while(index3 === index1 || index3 === index2){//Picks new index if index grnerated is already chosen.
  index3 = Math.floor(Math.random() * allProducts.length );
  };
console.log(index1);
};


//Function that will add 3 objects from allProducts array at indices generated by Choose3Products function to the DOM
//Displaying their image property.
function addToDOM(){
  choose3RandomNums();
  var display = document.getElementById("display");
  var newProduct1 = document.createElement("img");
  var newProduct2 = document.createElement("img");
  var newProduct3 = document.createElement("img");
  newProduct1.setAttribute("src", allProducts[index1].img);
  newProduct1.setAttribute("class", "product");
  newProduct2.setAttribute("src", allProducts[index2].img);
  newProduct2.setAttribute("class", "product");
  newProduct3.setAttribute("src", allProducts[index3].img);
  newProduct3.setAttribute("class", "product");
  display.appendChild(newProduct1);
  display.appendChild(newProduct2);
  display.appendChild(newProduct3);
  
}


//calling functions and methods
var bag = new createProduct("img/bag.jpg", "bag");
var banana = new createProduct("img/banana.jpg", "banana");
var bathroom = new createProduct("img/bathroom.jpg", "bathroom");
var boots = new createProduct("img/boots.jpg", "boots");
var breakfast = new createProduct("img/breakfast.jpg", "breakfast");

addToDOM();